### ISSUE TITLE
error when i attempt to inpaint an image in data folder

### ISSUE THREAD

**Issue by NerminSalem** [mdeff/giin#2]
hi 
i have another question, i m trying to inpaint an image and i generated the green mask as said in the readme but when i use inpaint('image'), i got the following error
![screenshot from 2017-08-23 12-18-42](https://user-images.githubusercontent.com/26221951/29611278-9cedb31e-8805-11e7-9d19-5c237a642cfc.png)
the image i want to inpaint:
![image](https://user-images.githubusercontent.com/26221951/29611294-a875b97a-8805-11e7-9eb9-e6cadce03000.png)
your help is really appreciated @mdeff

**Comment by mdeff** [comment]
Sorry I cannot help here. I don't know where it comes from and I don't use matlab anymore. Please post here if you find the issue.

**Comment by NerminSalem** [comment]
@nperraud can u help?
@mdeff thanks

**Comment by mdeff** [comment]
Maybe start with artificial images, like giin_image('vertical'), and move from there.

**Comment by NerminSalem** [comment]
thanks alot
